<?php require_once('./templates/header.phtml'); ?>
    <div class="container mt-4">
        <?php foreach ($categories as $category): ?>
            <div class="card mb-3">
                <div class="card-header bg-primary text-white">
                    <strong><?php echo $category->name; ?></strong>
                </div>
                <div class="card-body">
                    <?php if (isset($_SESSION['user']) && ($_SESSION['logged'] == true) && ($_SESSION['rol'] == 'admin')) : ?>
                    <a href="eliminarCategoria/<?php echo $category->id; ?>" class="btn btn-danger">Eliminar categoría</a>
                    <?php endif ?>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
    <?php require_once('./templates/footer.phtml'); ?>